services:
  postegre:
    image: postgres:13.13
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pg1234
      POSTGRES_USER: kubenews
      POSTGRES_DB: kubenews
  kubenews:
    image: josemoura212/kube-news:0.0.1
    build: 
      context: ./src
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_DATABASE: kubenews
      DB_USERNAME: kubenews
      DB_PASSWORD: pg1234
      DB_HOST: postegre

networks:
  kubenews_net:
    driver: bridge